## Defining Variables

In [ ]:
"Hello World"

In [ ]:
greeting = "Hello World" # this is a string variable (<- this is a comment)

In [ ]:
greeting

In [ ]:
greeting = "Hello World"
greeting

In [ ]:
print(greeting)

## Basic Math

In [1]:
a = 2
b = 15

Get the sum:

In [2]:
a + b

17

In [3]:
my_sum = a + b # get sum of a & b

In [4]:
# print sum

In [5]:
 my_sum

17

## Import libraries

numpy - Numerical Python (http://numpy.org)

In [1]:
import numpy as np

Define a numpy array

In [2]:
ages_list = [25, 30, 35, 40, 45] # this is a python list

In [3]:
ages = np.array(ages_list)

In [8]:
# you can also do this in a single line
ages = np.array([25, 30, 35, 40, 45, 50, 55])
ages

array([25, 30, 35, 40, 45, 50, 55])

Get specific elements - note that in Python, the index starts from 0

In [6]:
ages[0]

25

In [9]:
ages[6]

55

In [10]:
ages[-1] # this is the last element

55

In [11]:
ages[0:4] # goes from index = 0 to 3 (first 4 elements)

array([25, 30, 35, 40])

In [12]:
ages[:4] # goes from beginning to index 3 (same result as above)

array([25, 30, 35, 40])

In [13]:
ages[1:4] # goes from index = 1 to 3 (2nd to 4th elements)

array([30, 35, 40])

In [14]:
ages[1:] # goes from index = 1 to last element (same result as above)

array([30, 35, 40, 45, 50, 55])

In [15]:
ages[:] # goes from first to last element (same as ages)

array([25, 30, 35, 40, 45, 50, 55])

In [16]:
ages[::2] # keeps every 2nd element only

array([25, 35, 45, 55])

In [17]:
ages[::-1] # reverses order of elements

array([55, 50, 45, 40, 35, 30, 25])

Get subset of elements based on a acondition:

In [18]:
ages[ages<40]

array([25, 30, 35])

In [19]:
ages[ages<=40]

array([25, 30, 35, 40])

Get no. of elements / length of array

In [20]:
len(ages)

7

Get the mean, minimum, and maximum

In [23]:
ages_mean = np.mean(ages)
ages_mean

40.0

In [24]:
np.min(ages)

25

In [25]:
np.max(ages)

55